#!/usr/bin/env python3
"""Structural analysis on the VALID split.

Two difficulty axes, both computed only from the train graph (no leakage; the
gold answer is used only to assign a difficulty bucket, never for prediction):

1. Undirected simple path count (model-agnostic connectivity), <=3 hops.
2. Relation-aware directed program count (model-grounded rule-body availability):
   distinct relation programs of length <=3 over the reverse-augmented graph that
   reach the gold answer under walk semantics (target edge masked).

Baseline ranks (HoGRN/ConvE/TransE/TuckER plus optional AnyBURL) come from
external_predictions/valid_predictions. This baseline structural analysis
intentionally excludes PathBSR; PathBSR-specific structural analyses are
generated by scripts/pathbsr_experiments.py.
"""
from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path

try:
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt
except ModuleNotFoundError as exc:
    raise SystemExit(
        "Missing analysis dependency. Install the paper-analysis environment with:\n"
        "  python3 -m pip install -r requirements.txt"
    ) from exc

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from pathbsr import REVERSE_SUFFIX, load_dataset  # noqa: E402
from pathbsr.locations import data_root, workspace_root  # noqa: E402

DATA = data_root()
PRED = workspace_root() / "external_predictions" / "valid_predictions"
RESULTS = ROOT / "results"
CACHE_DIR = RESULTS / "cache"
DIAGNOSTIC_DIR = RESULTS / "diagnostics"
PATH_COUNT_DIR = RESULTS / "path_count"
CARDINALITY_DIR = RESULTS / "cardinality"
SPLIT = "valid"
DATASETS = ["FB15K-237-10", "FB15K-237-20", "FB15K-237-50", "NELL23K", "WD-singer", "WN18RR"]
BASELINES = ["HoGRN", "ConvE", "TransE", "TuckER"]
FB_SPLITS = ["FB15K-237-10", "FB15K-237-20", "FB15K-237-50"]
PAPER_PATHCOUNT_MODELS = ["TransE", "ConvE", "AnyBURL", "HoGRN"]
CAP = 101
PATH_ORDER = ["0", "1", "2-10", "11-100", ">100"]
PATH_LABEL = {"0": "0", "1": "1", "2-10": "2--10", "11-100": "11--100", ">100": ">100"}
CARD_ORDER = ["1-to-1", "1-to-N", "N-to-1", "N-to-N"]


def rev(r):
    return r[: -len(REVERSE_SUFFIX)] if r.endswith(REVERSE_SUFFIX) else r + REVERSE_SUFFIX


def bucket(c):
    return "0" if c == 0 else "1" if c == 1 else "2-10" if c <= 10 else "11-100" if c <= 100 else ">100"


# ---- axis 1: undirected simple path count ----------------------------------
def build_undirected(train):
    g = defaultdict(set)
    for h, _, t in train:
        if h != t:
            g[h].add(t)
            g[t].add(h)
    return g


def undirected_count(g, s, d, cap=CAP):
    if s == d:
        return 0
    sn, dn = g.get(s, set()), g.get(d, set())
    if not sn or not dn:
        return 0
    tot = 1 if d in sn else 0
    if tot >= cap:
        return cap
    tot += len((sn & dn) - {s, d})
    if tot >= cap:
        return cap
    left, right = sn - {d}, dn - {s}
    if left and right:
        small, big = (left, right) if len(left) <= len(right) else (right, left)
        for a in small:
            tot += len(g.get(a, set()) & big)
            if tot >= cap:
                return cap
    return min(tot, cap)


# ---- axis 2: relation-aware directed program count -------------------------
def build_directed_aug(train):
    out = defaultdict(lambda: defaultdict(set))
    for h, r, t in train:
        out[h][r].add(t)
        out[t][rev(r)].add(h)
    return out


def relprog_count(out, h, ans, masked, cap=CAP, scan=400):
    """Distinct relation programs (len<=3) reaching ans from h under walk
    semantics, masking the target edge. Capped at `cap` distinct programs; per
    node at most `scan` (relation,tail) edges scanned to bound dense FB cost."""
    if h == ans:
        return 0

    def edges(x):
        out_list = []
        for r, tails in out.get(x, {}).items():
            for t in tails:
                if (x, r, t) in masked:
                    continue
                out_list.append((r, t))
                if len(out_list) >= scan:
                    return out_list
        return out_list

    progs = set()
    h_edges = edges(h)
    # len 1
    for r1, t1 in h_edges:
        if t1 == ans:
            progs.add((r1,))
            if len(progs) >= cap:
                return cap
    # len 2 & 3
    for r1, x in h_edges:
        x_edges = edges(x)
        for r2, y in x_edges:
            if y == ans:
                progs.add((r1, r2))
                if len(progs) >= cap:
                    return cap
        for r2, y in x_edges:
            for r3, z in edges(y):
                if z == ans:
                    progs.add((r1, r2, r3))
                    if len(progs) >= cap:
                        return cap
    return min(len(progs), cap)


# ---- relation cardinality --------------------------------------------------
def infer_cardinality(train):
    rh, rt = defaultdict(list), defaultdict(list)
    for h, r, t in train:
        rh[r].append(h)
        rt[r].append(t)
    out = {}
    for r in rh:
        tph = len(rt[r]) / max(len(set(rh[r])), 1)
        hpt = len(rh[r]) / max(len(set(rt[r])), 1)
        out[r] = (
            "1-to-1" if hpt < 1.5 and tph < 1.5
            else "1-to-N" if hpt < 1.5
            else "N-to-1" if tph < 1.5
            else "N-to-N"
        )
    return out


def invert_card(c):
    return {"1-to-N": "N-to-1", "N-to-1": "1-to-N"}.get(c, c)


# ---- baseline ranks --------------------------------------------------------
def load_baseline_rr(model, ds):
    p = PRED / model / ds / "valid_query_summary.csv"
    df = pd.read_csv(p, usecols=["split", "query_index", "filtered_rank"])
    df = df[df.split == SPLIT].copy()
    df["model"] = model
    df["rr"] = 1.0 / df["filtered_rank"].astype(float)
    df["dataset"] = ds
    return df[["dataset", "model", "query_index", "rr"]]


def load_optional_baseline_rr(model, ds):
    """Load a baseline if its prediction file exists.

    This keeps paper-facing plots ready for AnyBURL while its ranks are still
    pending. The expected layout matches the other exported baselines:
    external_predictions/valid_predictions/<Model>/<Dataset>/valid_query_summary.csv
    with columns split, query_index, filtered_rank.
    """
    p = PRED / model / ds / "valid_query_summary.csv"
    if not p.exists():
        return None
    return load_baseline_rr(model, ds)


def build_features():
    rows = []
    for ds in DATASETS:
        train, valid, _ = load_dataset(DATA, ds)
        ug = build_undirected(train)
        dg = build_directed_aug(train)
        card = infer_cardinality(train)
        for ti, (h, r, t) in enumerate(valid):
            for direction, qi, qh, qr, ans, ctype in (
                ("tail", ti * 2, h, r, t, card.get(r, "Unknown")),
                ("head", ti * 2 + 1, t, rev(r), h, invert_card(card.get(r, "Unknown"))),
            ):
                masked = {(qh, qr, ans), (ans, rev(qr), qh)}
                uc = undirected_count(ug, qh, ans)
                rc = relprog_count(dg, qh, ans, masked)
                rows.append(
                    {
                        "dataset": ds, "split": SPLIT, "query_index": qi, "direction": direction,
                        "original_r": r, "path_count": uc, "path_bucket": bucket(uc),
                        "relpath_count": rc, "relpath_bucket": bucket(rc), "rel_type": ctype,
                    }
                )
        print(f"features {ds}: {len(valid)} triples", flush=True)
    return pd.DataFrame(rows)


def mrr_by(df, axis, models, order):
    piv = (
        df[df.model.isin(models)]
        .pivot_table(index=["dataset"], columns=[axis, "model"], values="rr", aggfunc="mean")
    )
    return piv


def plot_axis(long_df, axis, order, models, title, fname):
    ncols = 3
    nrows = int(np.ceil(len(DATASETS) / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(5 * ncols, 3.4 * nrows),
                             squeeze=False)
    # per-row shared y-axis (same ylim within a row; ticks shown on every subplot)
    gp = long_df[long_df.model.isin(models)].groupby(["dataset", axis, "model"])["rr"].mean()
    row_ymax = {}
    for r in range(nrows):
        row_ds = DATASETS[r * ncols:(r + 1) * ncols]
        m = gp[gp.index.get_level_values("dataset").isin(row_ds)].max()
        row_ymax[r] = np.ceil(float(m) * 10 + 1) / 10 if np.isfinite(m) else 1.0
    for i, ds in enumerate(DATASETS):
        ax = axes[i // ncols][i % ncols]
        sub = long_df[(long_df.dataset == ds) & (long_df.model.isin(models))]
        g = sub.groupby([axis, "model"])["rr"].mean().reset_index()
        present = [b for b in order if b in g[axis].unique()]
        x = np.arange(len(present))
        w = 0.8 / max(len(models), 1)
        for j, m in enumerate(models):
            vals = [g[(g[axis] == b) & (g.model == m)]["rr"].mean() for b in present]
            ax.bar(x + j * w, vals, w, label=m)
        ax.set_xticks(x + w * (len(models) - 1) / 2)
        ax.set_xticklabels(present, rotation=0, fontsize=8)
        ax.set_title(ds, fontsize=10)
        ax.set_ylim(0, row_ymax[i // ncols])
        if i % ncols == 0:
            ax.set_ylabel("MRR")
    for k in range(len(DATASETS), nrows * ncols):
        axes[k // ncols][k % ncols].axis("off")
    handles, labels = axes[0][0].get_legend_handles_labels()
    fig.tight_layout(rect=[0, 0, 1, 0.92])
    fig.legend(handles, labels, loc="upper center", bbox_to_anchor=(0.5, 0.985),
               ncol=len(models), fontsize=9, frameon=False)
    fig.suptitle(title, y=1.04, fontsize=12)
    fig.savefig(DIAGNOSTIC_DIR / fname, dpi=130, bbox_inches="tight")
    plt.close(fig)
    print("saved", (DIAGNOSTIC_DIR / fname).relative_to(ROOT))


def plot_fb_pathcount_grouped_bar(long_df):
    """Paper-facing FB sparse-split path-count grouped bar chart.

    One subplot per FB split; x-axis is undirected path-count bucket and each
    bar group compares existing methods. AnyBURL is intentionally optional and will appear
    automatically once its valid_query_summary.csv files are exported.
    """
    sub = long_df[
        (long_df.dataset.isin(FB_SPLITS))
        & (long_df.model.isin(PAPER_PATHCOUNT_MODELS))
    ].copy()
    available_models = [m for m in PAPER_PATHCOUNT_MODELS if m in set(sub.model)]
    missing_models = [m for m in PAPER_PATHCOUNT_MODELS if m not in set(sub.model)]
    if not available_models:
        print("paper FB path-count grouped bar plot skipped: no requested model data found.")
        return

    fig, axes = plt.subplots(1, len(FB_SPLITS), figsize=(13.5, 3.7), sharey=True)
    colors = {
        "TransE": "#1f77b4",
        "ConvE": "#ff7f0e",
        "AnyBURL": "#9467bd",
        "HoGRN": "#2ca02c",
    }
    x = np.arange(len(PATH_ORDER))
    width = 0.78 / max(len(available_models), 1)
    offsets = (np.arange(len(available_models)) - (len(available_models) - 1) / 2) * width
    for ax, ds in zip(axes, FB_SPLITS):
        g = (
            sub[sub.dataset == ds]
            .groupby(["path_bucket", "model"])["rr"]
            .mean()
            .reset_index()
        )
        for offset, model in zip(offsets, available_models):
            vals = []
            for bucket_name in PATH_ORDER:
                v = g[(g.path_bucket == bucket_name) & (g.model == model)]["rr"]
                vals.append(np.nan if v.empty else float(v.iloc[0]))
            ax.bar(x + offset, vals, width=width, label=model, color=colors.get(model))
        ax.set_title(ds)
        ax.set_xticks(x)
        ax.set_xticklabels([PATH_LABEL[b] for b in PATH_ORDER], fontsize=9)
        ax.set_xlabel("Path-count bucket")
        ax.grid(True, axis="y", linestyle="--", linewidth=0.6, alpha=0.45)
    axes[0].set_ylabel("MRR")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.08),
        ncol=len(available_models),
        frameon=False,
    )
    fig.tight_layout(rect=[0, 0.08, 1, 1])
    paper_png = PATH_COUNT_DIR / "fb_pathcount_mrr_grouped_bar.png"
    fig.savefig(paper_png, dpi=180, bbox_inches="tight")
    plt.close(fig)
    if missing_models:
        print(
            f"saved {paper_png.relative_to(ROOT)}; "
            f"pending model data not shown: {', '.join(missing_models)}"
        )
    else:
        print("saved", paper_png.relative_to(ROOT))


def plot_fb_cardinality_grouped_bar(long_df):
    """Paper-facing FB sparse-split cardinality grouped bar chart."""
    sub = long_df[
        (long_df.dataset.isin(FB_SPLITS))
        & (long_df.model.isin(PAPER_PATHCOUNT_MODELS))
    ].copy()
    available_models = [m for m in PAPER_PATHCOUNT_MODELS if m in set(sub.model)]
    missing_models = [m for m in PAPER_PATHCOUNT_MODELS if m not in set(sub.model)]
    if not available_models:
        print("paper FB cardinality bar plot skipped: no requested model data found.")
        return

    fig, axes = plt.subplots(1, len(FB_SPLITS), figsize=(13.5, 3.7), sharey=True)
    colors = {
        "TransE": "#1f77b4",
        "ConvE": "#ff7f0e",
        "AnyBURL": "#9467bd",
        "HoGRN": "#2ca02c",
    }
    x = np.arange(len(CARD_ORDER))
    width = 0.78 / max(len(available_models), 1)
    offsets = (np.arange(len(available_models)) - (len(available_models) - 1) / 2) * width
    for ax, ds in zip(axes, FB_SPLITS):
        g = (
            sub[sub.dataset == ds]
            .groupby(["rel_type", "model"])["rr"]
            .mean()
            .reset_index()
        )
        for offset, model in zip(offsets, available_models):
            vals = []
            for rel_type in CARD_ORDER:
                v = g[(g.rel_type == rel_type) & (g.model == model)]["rr"]
                vals.append(np.nan if v.empty else float(v.iloc[0]))
            ax.bar(x + offset, vals, width=width, label=model, color=colors.get(model))
        ax.set_title(ds)
        ax.set_xticks(x)
        ax.set_xticklabels(CARD_ORDER, rotation=20, ha="right", fontsize=9)
        ax.set_xlabel("Relation cardinality")
        ax.grid(True, axis="y", linestyle="--", linewidth=0.6, alpha=0.45)
    axes[0].set_ylabel("MRR")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.11),
        ncol=len(available_models),
        frameon=False,
    )
    fig.tight_layout(rect=[0, 0.1, 1, 1])
    paper_png = CARDINALITY_DIR / "fb_cardinality_mrr_grouped_bar.png"
    fig.savefig(paper_png, dpi=180, bbox_inches="tight")
    plt.close(fig)
    if missing_models:
        print(
            f"saved {paper_png.relative_to(ROOT)}; "
            f"pending model data not shown: {', '.join(missing_models)}"
        )
    else:
        print("saved", paper_png.relative_to(ROOT))


def write_fb_pathbucket_share_table(feats):
    """Write paper-facing query-share table for the three FB sparse splits."""
    fb = feats[feats.dataset.isin(FB_SPLITS)].copy()
    dist = (
        fb.assign(n=1)
        .pivot_table(index="dataset", columns="path_bucket", values="n", aggfunc="sum", fill_value=0)
        .reindex(index=FB_SPLITS, columns=PATH_ORDER, fill_value=0)
    )
    share = (dist.div(dist.sum(1), axis=0) * 100).round(1)
    share = share.rename(columns=PATH_LABEL)
    csv_out = PATH_COUNT_DIR / "fb_pathbucket_query_share.csv"
    tex_out = PATH_COUNT_DIR / "fb_pathbucket_query_share.tex"
    share.to_csv(csv_out)
    latex = share.to_latex(
        index=True,
        escape=False,
        float_format="%.1f",
        column_format="lrrrrr",
        caption="Query share by undirected path-count bucket on FB15K-237 sparse validation splits.",
        label="tab:fb-path-count-query-share",
    )
    tex_out.write_text(latex, encoding="utf-8")
    print("saved", csv_out.relative_to(ROOT))
    print("saved", tex_out.relative_to(ROOT))


def write_fb_cardinality_share_table(feats):
    """Write paper-facing query-share table by relation cardinality."""
    fb = feats[feats.dataset.isin(FB_SPLITS)].copy()
    dist = (
        fb.assign(n=1)
        .pivot_table(index="dataset", columns="rel_type", values="n", aggfunc="sum", fill_value=0)
        .reindex(index=FB_SPLITS, columns=CARD_ORDER, fill_value=0)
    )
    share = (dist.div(dist.sum(1), axis=0) * 100).round(1)
    csv_out = CARDINALITY_DIR / "fb_cardinality_query_share.csv"
    tex_out = CARDINALITY_DIR / "fb_cardinality_query_share.tex"
    share.to_csv(csv_out)
    latex = share.to_latex(
        index=True,
        escape=False,
        float_format="%.1f",
        column_format="lrrrr",
        caption="Share of validation queries by relation cardinality on FB15K-237 sparsity splits.",
        label="tab:fb-cardinality-query-share",
    )
    tex_out.write_text(latex, encoding="utf-8")
    print("saved", csv_out.relative_to(ROOT))
    print("saved", tex_out.relative_to(ROOT))


def main():
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    DIAGNOSTIC_DIR.mkdir(parents=True, exist_ok=True)
    PATH_COUNT_DIR.mkdir(parents=True, exist_ok=True)
    CARDINALITY_DIR.mkdir(parents=True, exist_ok=True)
    feat_csv = CACHE_DIR / "structural_valid_features.csv"
    if feat_csv.exists():
        print("loading cached features", feat_csv)
        feats = pd.read_csv(feat_csv)
    else:
        feats = build_features()
        feats.to_csv(feat_csv, index=False)

    # ranks: existing methods only; this baseline analysis intentionally excludes PathBSR.
    rank_frames = [load_baseline_rr(m, ds) for m in BASELINES for ds in DATASETS]
    optional_frames = []
    for m in PAPER_PATHCOUNT_MODELS:
        if m in BASELINES:
            continue
        for ds in DATASETS:
            maybe = load_optional_baseline_rr(m, ds)
            if maybe is not None:
                optional_frames.append(maybe)
    if optional_frames:
        rank_frames.extend(optional_frames)
        print(
            "Optional baseline detail merged:",
            ", ".join(sorted({df["model"].iloc[0] for df in optional_frames})),
        )
    ranks = pd.concat(rank_frames, ignore_index=True)
    models = list(BASELINES)
    optional_models = sorted({df["model"].iloc[0] for df in optional_frames})
    models = models + [m for m in optional_models if m not in models]
    print("Structural baseline analysis excludes PathBSR by design.")

    long_df = ranks.merge(feats, on=["dataset", "query_index"], how="inner")
    long_df.to_csv(CACHE_DIR / "structural_valid_long.csv", index=False)

    # Paper-facing path-count outputs for the FB sparse
    # split trend analysis. These do not replace the older notebook/bar-chart
    # outputs below; they are additional clean artifacts for the paper.
    write_fb_pathbucket_share_table(feats)
    write_fb_cardinality_share_table(feats)
    plot_fb_pathcount_grouped_bar(long_df)
    plot_fb_cardinality_grouped_bar(long_df)

    # distribution table (model-agnostic)
    dist = (
        feats.assign(n=1)
        .pivot_table(index="dataset", columns="path_bucket", values="n", aggfunc="sum", fill_value=0)
        .reindex(columns=PATH_ORDER, fill_value=0)
    )
    (dist.div(dist.sum(1), axis=0) * 100).round(1).to_csv(CACHE_DIR / "structural_valid_pathbucket_share.csv")

    base_only = list(BASELINES)
    # axis 1: undirected
    plot_axis(long_df, "path_bucket", PATH_ORDER, base_only,
              "MRR by undirected path-count bucket (valid, existing methods)",
              "diagnostic_pathbucket_mrr_baselines.png")
    # axis 2: relation-aware
    plot_axis(long_df, "relpath_bucket", PATH_ORDER, base_only,
              "MRR by relation-program bucket (valid, existing methods)",
              "diagnostic_relpathbucket_mrr_baselines.png")
    # cardinality
    plot_axis(long_df, "rel_type", CARD_ORDER, base_only,
              "MRR by relation cardinality (valid, existing methods)",
              "diagnostic_cardinality_mrr_baselines.png")

    print("\n=== valid undirected path-bucket share (%) ===")
    print((dist.div(dist.sum(1), axis=0) * 100).round(1).to_string())


if __name__ == "__main__":
    main()
